---
- name: Create event-gateway namespace
  block:
    - copy: src=eg-namespace.yaml dest=/tmp/eg-namespace.yaml
    - command: kubectl apply -f /tmp/eg-namespace.yaml

- name: Create etcd statefulset and service
  block:
    - copy: src=etcd.yaml dest=/tmp/etcd.yaml
    - command: kubectl apply -f /tmp/etcd.yaml

- name: Create event-gateway deployment and service
  block:
    - copy: src=event-gateway.yaml dest=/tmp/event-gateway.yaml
    - command: kubectl apply -f /tmp/event-gateway.yaml
